CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE public.chat (
                                id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                created_at TIMESTAMP(6),
                                title      VARCHAR(255)
);

ALTER TABLE public.chat OWNER TO postgres;


CREATE TABLE public.chat_entry (
                                id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                content    TEXT,
                                created_at TIMESTAMP(6),
                                role       VARCHAR(255)
                                CONSTRAINT chat_entry_role_check
                                CHECK ((role)::TEXT = ANY (ARRAY['USER'::CHARACTER VARYING, 'ASSISTANT'::CHARACTER VARYING]::TEXT[])),
                                chat_id    BIGINT
                                CONSTRAINT fkqcc1bnu77jh530e61twlq52ja
                                REFERENCES public.chat(id)
);

ALTER TABLE public.chat_entry OWNER TO postgres;



CREATE TABLE IF NOT EXISTS loaded_document (
    id            SERIAL PRIMARY KEY,
    filename      VARCHAR(255) NOT NULL,
    content_hash  VARCHAR(64) NOT NULL,
    document_type VARCHAR(10) NOT NULL,
    chunk_count   INTEGER,
    loaded_at     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT unique_document UNIQUE (filename, content_hash)
    );


CREATE INDEX IF NOT EXISTS idx_loaded_documents_filename
    ON loaded_document(filename);


CREATE TABLE IF NOT EXISTS users (
                       id BIGSERIAL PRIMARY KEY,
                       username VARCHAR(30) NOT NULL UNIQUE,
                       password VARCHAR(80) NOT NULL,
                       email VARCHAR(50) UNIQUE,
                       created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                       updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                       registration_status VARCHAR(30) NOT NULL,
                       last_login TIMESTAMP,
                       deleted BOOLEAN NOT NULL DEFAULT false
);

CREATE TABLE IF NOT EXISTS refresh_token (
                               id SERIAL PRIMARY KEY,
                               token VARCHAR(128) NOT NULL,
                               created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                               user_id BIGINT NOT NULL,
                               CONSTRAINT FK_refresh_tokens_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
                               CONSTRAINT refresh_token_UNIQUE UNIQUE (user_id, id)
);


CREATE TABLE IF NOT EXISTS vector_store (
    id        VARCHAR(255) PRIMARY KEY,
    content   TEXT,
    metadata  JSON,
    embedding VECTOR(1024)
    );


CREATE INDEX IF NOT EXISTS vector_store_hnsw_index
    ON vector_store USING hnsw (embedding vector_cosine_ops);

